{% set name = "celery-eternal" %}
{% set version = "0.1.1" %}
{% set sha256 = "7ad22d9a26ce3c7774d73d52ae556d68e214122acbc50c6e1e7e358401b96ac1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3.0
  run:
    - python
    - celery >=4.1.0
    - celery-singleton >=0.1.1
    - redis-py >=2.10.5

test:
  imports:
    - celery_eternal
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs celery_eternal

about:
  home: https://celery-eternal.readthedocs.io
  doc_url: https://celery-eternal.readthedocs.io
  dev_url: https://github.com/lpsinger/celery-eternal
  license: GPLv2+
  license_family: GPL
  license_file: LICENSE.md
  summary: Celery task subclass for jobs that should run forever

extra:
  recipe-maintainers:
    - duncanmmacleod
