travis:
  secure:
    BINSTAR_TOKEN: bOcw4gG4nu//clFWkfVwr/HMNMEPvvitvFguobq83kzp8ld8mz02nZMGmFskmr80xNiaxLWPap97nfPVPPRBGWoEH6MjnTw6AQ1mrnvRpy6JwApopGGO7hLCq7yE4+FHChdq2QyJ5oZaHNFHSq6S/A4I+5OCb063VULOLhy3YG3xisrIqnla0qpnoK7VCi1A40agnPYDHitbj46NmGQG1HYq/Rm59oSfXtN0qm7iioopBEgp79zQxlHJZjNu4AoXv39YE2NT5cFoNk9rS+vkBluJI/KPwVaNZxqV0tBt0J+xu/lnBVU5hArpFANV7T5uMPKQukuhQpyLPXNSMkSuvsnveaR2SXjk/XyD8n81/MvHsxB2MC9qObEV1RNUL7/yTQ/QghY3wpaQH723SV2FgTgEW4rFqRtussviBlEoBnM1yxmYvhk/1tUgplqy0Hfqp6suS00GJbVQ34DX9rS8iEIFHTCtkzASlAZhv+H2Qhl9xQhGis95+mezxzE4SKn/cev8iYefkMhLeidBT8K68tCfdFvj4CxlF2fwGR4XtI1dsOn7/M8pEh0zGf1WYVpMMI8OFdfdOdJwNJ2PYkdz85lpazuP+KD60Vi6chQfHNIC1IlMbvQQbmp+NPu4dZmZHrE164cxT8/bNGGM1Xe3W8pKxzsFQY9U1qCTOSaP3eg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
